spring.application.name=user-management

spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
app.storage.identity-documents-dir=./storage/identity-documents


# External notification/SMS gateway
app.notification.base-url=http://localhost:9090
app.notification.api-key=dev-api-key

# MFA OTP settings
app.mfa.otp-ttl-seconds=300
app.mfa.max-attempts=5

spring.ldap.urls=ldap://ldap.example.com:389
spring.ldap.base=dc=example,dc=com
spring.ldap.username=cn=admin,dc=example,dc=com
spring.ldap.password=adminpassword